volumes:
  db-store:
  psysh-store:

configs:
  db-config:
    file: ./infra/docker/pgsql/postgresql.conf

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
      target: ${APP_BUILD_TARGET:-development}
    volumes:
      - type: bind
        source: ./src
        target: /workspace
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_ENV=${APP_ENV:-local}
      - APP_URL=${APP_URL:-http://localhost}
      - LOG_CHANNEL=${LOG_CHANNEL:-stderr}
      - LOG_STDERR_FORMATTER=${LOG_STDERR_FORMATTER:-Monolog\Formatter\JsonFormatter}
      - DB_CONNECTION=${DB_CONNECTION:-pgsql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-j_access}
      - DB_USERNAME=${DB_USERNAME:-cande00}
      - DB_PASSWORD=${DB_PASSWORD:-cande00}

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PUBLISHED_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./src
        target: /workspace

  db:
    build:
      context: .
      dockerfile: ./infra/docker/pgsql/Dockerfile
    ports:
      - target: 5432
        published: ${DB_PUBLISHED_PORT:-5432}
        protocol: tcp
        mode: host
    #configs:
    #  - source: db-config
    #    target: /etc/postgresql.conf
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      - POSTGRES_DB=${DB_DATABASE:-j_access}
      - POSTGRES_USER=${DB_USERNAME:-cande00}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-cande00}
      - POSTGRES_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - POSTGRES_INITDB_ARGS=--encoding=EUC_JP --locale=ja_JP.eucJP

  mailpit:
    image: axllent/mailpit
    ports:
      - target: 8025
        published: ${MAILPIT_PUBLISHED_PORT:-8025}
        protocol: tcp
        mode: host
